r"""
rtl-auto / src / generator.py — 全量生成器（P2）

流程：
  1. 根据 TOML 生成顶层 .v 骨架（AUTO 标记）
  2. emacs 展开（AUTOARG + AUTOINPUT/OUTPUT + AUTOWIRE + AUTOINST）
  3. wires 规则后处理（覆盖端口连接）
  4. 清理 AUTO 标记
  5. Verible 格式化
"""
import os, re

from .parser import InstanceBlock
from .expander import expand_auto, get_backend
from .formatter import format_file


def generate_full(cfg: dict) -> str:
    """
    从 TOML 配置生成完整顶层模块。
    返回生成的文件路径。
    """
    top_file = cfg["top"]["output"]
    top_module = cfg["top"]["module"]
    instances = cfg.get("_instances", [])
    wires_config = cfg.get("wires", [])
    params_config = cfg.get("params", [])
    no_format = not cfg.get("options", {}).get("auto_format", True)

    # ---- Phase 1: 生成骨架 ----
    skeleton = _build_skeleton(top_module, instances, params_config)

    tmp_file = top_file + ".tmp"
    os.makedirs(os.path.dirname(tmp_file) or ".", exist_ok=True)
    with open(tmp_file, 'w') as f:
        f.write(skeleton)

    # ---- Phase 2: 收集 library_dirs ----
    lib_dirs = {os.path.dirname(os.path.abspath(top_file))}
    for inst in instances:
        if inst.get("file"):
            lib_dirs.add(os.path.dirname(os.path.abspath(inst["file"])))

    # ---- Phase 3: emacs 展开 ----
    print("[INFO] Running verilog-mode full expansion (AUTOARG + AUTOINPUT/OUTPUT + AUTOWIRE + AUTOINST)...")
    stderr = expand_auto(tmp_file, library_dirs=list(lib_dirs))
    if stderr and "Error" in stderr:
        print("[WARN] emacs stderr: " + stderr[:200])

    with open(tmp_file) as f:
        expanded = f.read()

    # ---- Phase 4: wires 规则后处理 ----
    if wires_config:
        print("[INFO] Applying wires rules...")
        expanded = _apply_wires_postprocess(expanded, instances, wires_config)
        expanded = _fix_declarations(expanded, instances)

    # ---- Phase 5: 清理标记 ----
    cleaned = InstanceBlock.remove_auto_markers(expanded)
    cleaned = re.sub(r'\n\s*\n\s*\n', '\n\n', cleaned)

    with open(tmp_file, 'w') as f:
        f.write(cleaned)

    # ---- Phase 6: Verible 格式化 ----
    if not no_format:
        if format_file(tmp_file):
            print("[INFO] Verible formatted")
        else:
            print("[WARN] verible-verilog-format not found")

    os.replace(tmp_file, top_file)
    print("[DONE] Generated: " + top_file)
    return top_file


# ---------------------------------------------------------------------------
# 骨架生成
# ---------------------------------------------------------------------------

SKELETON = """// {module_name} — auto-generated by rtl-auto
// DO NOT EDIT DIRECTLY — use `rtl-auto full -c <config.toml>`

module {module_name} (/*AUTOARG*/);

  /*AUTOINPUT*/
  /*AUTOOUTPUT*/
  /*AUTOWIRE*/

{instances}

endmodule
"""

INST_TEMPLATE = """  // Instance: {inst_name} ({module}{params_comment})
  {module}{params_block} {inst_name} (
      /*AUTOINST*/
  );"""


def _build_skeleton(module_name: str, instances: list, params_config: list) -> str:
    """生成带 AUTO 标记的顶层骨架"""
    inst_lines = []

    for inst in instances:
        params_block = ""
        params_comment = ""

        if inst.get("params"):
            param_parts = []
            for k, v in inst["params"].items():
                param_parts.append('.' + k + '(' + v + ')')
            params_block = " #(\n    " + ",\n    ".join(param_parts) + "\n  )"
            params_comment = ", " + ", ".join(k + '=' + v for k, v in inst["params"].items())

        inst_lines.append(INST_TEMPLATE.format(
            inst_name=inst["name"],
            module=inst["module"],
            params_block=params_block,
            params_comment=params_comment,
        ))

    return SKELETON.format(
        module_name=module_name,
        instances="\n\n".join(inst_lines),
    )


# ---------------------------------------------------------------------------
# wires 后处理
# ---------------------------------------------------------------------------

def _apply_wires_postprocess(text: str, instances: list, wires_config: list) -> str:
    """
    在 emacs 展开结果上直接应用 wires 规则。
    提取每个 instance 的端口连接，匹配规则后替换。
    """
    import re as _re
    parser = InstanceBlock(text)

    for wire_rule in wires_config:
        scope = wire_rule.get("scope", "")
        if scope not in ("inst",):
            continue

        inst_patterns = wire_rule.get("insts", [])
        rules = wire_rule.get("rules", [])

        # 先收集所有匹配的实例（保留顺序）
        matched_insts = []
        for inst in instances:
            if _match_inst(inst["name"], inst_patterns):
                matched_insts.append(inst)

        for inst_idx, inst in enumerate(matched_insts):
            block = parser.locate(inst["module"], inst["name"])
            if not block:
                continue

            # 提取当前端口连接
            ports = InstanceBlock.extract_ports(text, block)
            port_map = {p["name"]: p for p in ports}

            # 应用每条 rule
            for rule_entry in rules:
                port_pat = rule_entry[0]
                signal_tmpl = rule_entry[1]

                matched = _match_port(port_pat, list(port_map.keys()))
                for pname in matched:
                    signal = signal_tmpl.format(
                        port=pname,
                        inst_idx=inst_idx,
                        inst_name=inst["name"],
                    )
                    port_map[pname]["signal"] = signal

            # 重建 instance 块
            new_body = _format_connections(list(port_map.values()))
            if new_body:
                text = parser.replace_body(block, new_body)
                parser = InstanceBlock(text)

    return text


def _match_inst(inst_name: str, patterns: list) -> bool:
    """检查实例名是否匹配正则列表"""
    import re as _re
    for pat in patterns:
        is_regex = pat.startswith("~")
        pattern = _re.compile(pat[1:] if is_regex else '^' + _re.escape(pat) + '$')
        if pattern.match(inst_name):
            return True
    return False


def _match_port(port_pat: str, port_names: list) -> list:
    """匹配端口名列表"""
    import re as _re
    is_regex = port_pat.startswith("~")
    if is_regex:
        pattern = _re.compile(port_pat[1:])
        return [p for p in port_names if pattern.match(p)]
    return [port_pat] if port_pat in port_names else []


def _format_connections(ports: list) -> str:
    """格式化端口连接列表为 .port(signal) 文本块"""
    lines = []
    inputs = [p for p in ports if p.get("is_input")]
    outputs = [p for p in ports if not p.get("is_input")]

    if outputs:
        lines.append("      // Outputs")
        for p in outputs:
            sig = p["signal"]
            lines.append('      .' + p['name'] + '  (' + sig + '),')

    if inputs:
        lines.append("      // Inputs")
        for p in inputs:
            sig = p["signal"]
            lines.append('      .' + p['name'] + '  (' + sig + '),')

    if lines:
        lines[-1] = lines[-1].rstrip(",")
    # 用 \n 连接，前后加空行匹配括号内格式
    return "\n" + "\n".join(lines)


def _fix_declarations(text: str, instances: list) -> str:
    """
    扫描 instance 块中使用的信号名，为缺失的信号补上 wire 声明。
    在 // End of automatics 之前插入。
    """
    import re as _re
    parser = InstanceBlock(text)

    # 收集所有 instance 连接中使用的信号名
    used_signals = set()
    for inst in instances:
        block = parser.locate(inst["module"], inst["name"])
        if block:
            ports = InstanceBlock.extract_ports(text, block)
            for p in ports:
                sig = p["signal"].strip()
                if sig and not _is_constant(sig):
                    # 去掉位宽后缀: data_out[7:0] → data_out
                    sig = _re.sub(r'\[[^\]]*\]$', '', sig)
                    used_signals.add(sig)

    # 解析已有的声明
    declared = set()
    # input/output/wire 声明
    for m in _re.finditer(r'^\s*(input|output|wire)\s+(?:\[\S+\]\s+)?(\w+)', text, _re.MULTILINE):
        declared.add(m.group(2))

    # 顶层端口列表中的信号
    port_list_match = _re.search(r'module\s+\w+\s*\(([^)]*)\)', text, _re.DOTALL)
    if port_list_match:
        for sig in _re.findall(r'(\w+)', port_list_match.group(1)):
            declared.add(sig)

    # 找出缺失的
    missing = used_signals - declared
    if not missing:
        return text

    # 在 // End of automatics 之前插入 wire 声明
    end_marker = "// End of automatics"
    end_pos = text.rfind(end_marker)
    if end_pos < 0:
        return text

    # 在 End marker 之前插入
    new_wires = "\n".join('  wire ' + sig + ';' for sig in sorted(missing))
    text = text[:end_pos] + '\n' + new_wires + '\n  ' + text[end_pos:]

    return text


def _is_constant(s: str) -> bool:
    """判断信号值是否为 Verilog 常量"""
    import re as _re
    return bool(_re.match(r"^\d+'[bhod]", s))
