// soc_top — auto-generated by rtl-auto
// DO NOT EDIT DIRECTLY — use `rtl-auto full -c <config.toml>`

module soc_top (
    // Outputs
    wready,
    valid_out,
    error,
    data_out,
    bvalid,
    bresp,
    awready,
    // Inputs
    wvalid,
    wstrb,
    wdata,
    valid_in,
    rst_n,
    data_in,
    clk,
    bready,
    awvalid,
    awaddr
);
  // Beginning of automatic inputs (from unused autoinst inputs)
  input [ADDR_W-1:0] awaddr;  // To u01_axi_slave_0 of axi_slave.v, ...
  input awvalid;  // To u01_axi_slave_0 of axi_slave.v, ...
  input bready;  // To u01_axi_slave_0 of axi_slave.v, ...
  input clk;  // To u00_sub_module_0 of sub_module.v, ...
  input [7:0] data_in;  // To u00_sub_module_0 of sub_module.v
  input rst_n;  // To u00_sub_module_0 of sub_module.v, ...
  input valid_in;  // To u00_sub_module_0 of sub_module.v
  input [DATA_W-1:0] wdata;  // To u01_axi_slave_0 of axi_slave.v, ...
  input [DATA_W/8-1:0] wstrb;  // To u01_axi_slave_0 of axi_slave.v, ...
  input wvalid;  // To u01_axi_slave_0 of axi_slave.v, ...
  // End of automatics
  // Beginning of automatic outputs (from unused autoinst outputs)
  output awready;  // From u01_axi_slave_0 of axi_slave.v, ...
  output [1:0] bresp;  // From u01_axi_slave_0 of axi_slave.v, ...
  output bvalid;  // From u01_axi_slave_0 of axi_slave.v, ...
  output [7:0] data_out;  // From u00_sub_module_0 of sub_module.v
  output error;  // From u00_sub_module_0 of sub_module.v
  output valid_out;  // From u00_sub_module_0 of sub_module.v
  output wready;  // From u01_axi_slave_0 of axi_slave.v, ...
  // End of automatics
  // Instance: u00_sub_module_0 (sub_module)
  sub_module u00_sub_module_0 (
      // Outputs
      .data_out(data_out[7:0]),
      .valid_out(valid_out),
      .error(error),
      // Inputs
      .clk(clk),
      .rst_n(rst_n),
      .data_in(data_in[7:0]),
      .valid_in(valid_in)
  );

  // Instance: u01_axi_slave_0 (axi_slave, DATA_W=32, ADDR_W=64)
  axi_slave #(
      .DATA_W(32),
      .ADDR_W(64)
  ) u01_axi_slave_0 (
      // Outputs
      .awready(awready),
      .wready(wready),
      .bresp(bresp[1:0]),
      .bvalid(bvalid),
      // Inputs
      .clk(clk),
      .rst_n(rst_n),
      .awaddr(awaddr[ADDR_W-1:0]),
      .awvalid(awvalid),
      .wdata(wdata[DATA_W-1:0]),
      .wstrb(wstrb[DATA_W/8-1:0]),
      .wvalid(wvalid),
      .bready(bready)
  );

  // Instance: u01_axi_slave_1 (axi_slave, DATA_W=64, ADDR_W=128)
  axi_slave #(
      .DATA_W(64),
      .ADDR_W(128)
  ) u01_axi_slave_1 (
      // Outputs
      .awready(awready),
      .wready(wready),
      .bresp(bresp[1:0]),
      .bvalid(bvalid),
      // Inputs
      .clk(clk),
      .rst_n(rst_n),
      .awaddr(awaddr[ADDR_W-1:0]),
      .awvalid(awvalid),
      .wdata(wdata[DATA_W-1:0]),
      .wstrb(wstrb[DATA_W/8-1:0]),
      .wvalid(wvalid),
      .bready(bready)
  );

endmodule
